language: go

go: 1.11.x
go_import_path: github.com/kubevirt/kubernetes-device-plugins

script: make build test docker-build

deploy:
  - provider: script
    skip_cleanup: true
    script: docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" quay.io && make docker-push
    on:
      branch: master
